[package]
name = "nora_endian"
version = "0.1.2"
edition = "2021"
license = "0BSD"
repository = "https://github.com/Demindiro/nora_endian"
description = "Crate to make dealing with endianness convenient."
documentation = "https://docs.rs/nora_endian"
