[package]
name = "nora_endian"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Demindiro/nora_endian"
description = "Crate to make dealing with endianness convenient."
